stages:
  - install
  - check

before_script:


Prepare:
  stage: install
  image: "registry.gitlab.com/rasarts/notification_center/flutter:master"

  artifacts:
    expire_in: 7 days
    when: on_success
    paths:
      - .

  before_script:
    - flutter --version

  script:
    - rm -rf example/
    - flutter packages get --offline
    - flutter packages pub run build_runner build

Complexity:
  stage: check
  image: "google/dart:dev"
  dependencies:
    - Prepare

  before_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - pub global activate --source git https://github.com/Rasarts/codemetrics.git

  script:
    - echo "Warning complexity begin from $BeginWarningComplexityNumber"
    - echo "Error complexity begin from $BeginErrorComplexityNumber."

    - dart-codemetrics --begin-warning-complexity-number=$BeginWarningComplexityNumber --begin-error-complexity-number=$BeginErrorComplexityNumber

Tests:
  stage: check
  image: "registry.gitlab.com/rasarts/notification_center/flutter:master"
  dependencies:
    - Prepare

  artifacts:
    expire_in: 3 days
    when: on_success
    paths:
      - coverage

  before_script:
    - flutter --version

  script:
    # Run unit and integration tests if it needed
    - flutter test --coverage
    - genhtml coverage/lcov.info -o coverage
