name: notification_center
description: Show notifications in app.
version: 0.2.0
homepage: https://github.com/Hecatoncheir/notification_center

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.1
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.2.1

flutter:
  uses-material-design: true
