name: notification_center
<<<<<<< HEAD
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"
=======
description: Display custom notifications.
version: 0.1.4
author: Vostrikov Vitaliy
homepage: https://github.com/Hecatoncheir/notification_center

environment:
  sdk: ">=2.12.0 <3.0.0"
>>>>>>> 9515f7a440562ce3e94d38cd3e272d35c9fd8baf

dependencies:
  flutter:
    sdk: flutter

  pedantic: ^1.10.0
  bloc: ^7.0.0-nullsafety.1
  flutter_bloc: ^7.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
<<<<<<< HEAD

  # To add assets to your package, add an assets section, like this:
=======
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.call.notification_center
    pluginClass: NotificationCenterPlugin
  # To add assets to your plugin package, add an assets section, like this:
>>>>>>> 9515f7a440562ce3e94d38cd3e272d35c9fd8baf
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
<<<<<<< HEAD

  # To add custom fonts to your package, add a fonts section here,
=======
  # To add custom fonts to your plugin package, add a fonts section here,
>>>>>>> 9515f7a440562ce3e94d38cd3e272d35c9fd8baf
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
